"""
Nimblize - PostgreSQL Connection & Persistence Layer
Handles all read/write operations against the Nimblize production database.
"""

import os
import json
import uuid
from typing import Dict, Any, List, Optional
from contextlib import contextmanager
import psycopg2
from psycopg2 import pool
from psycopg2.extras import RealDictCursor, Json

# H4/M4 FIX: Register pgvector adapter so List[float] is correctly
# serialized to PostgreSQL's vector type.
try:
    from pgvector.psycopg2 import register_vector
    _PGVECTOR_AVAILABLE = True
except ImportError:
    _PGVECTOR_AVAILABLE = False
    print("[DB] ⚠️  pgvector adapter not available — vector inserts will fail.")

# H3 FIX: ThreadedConnectionPool prevents connection exhaustion under load.
# Min=2, Max=10 connections shared across uvicorn workers.
# H2 FIX: resolved lazily at first connection, not at import time.
_pool: pool.ThreadedConnectionPool = None


def _get_pool() -> pool.ThreadedConnectionPool:
    global _pool
    if _pool is None:
        db_url = os.environ.get(
            "DATABASE_URL",
            "postgresql://nimblize:nimblize@localhost:5432/nimblize"
        )
        _pool = pool.ThreadedConnectionPool(
            minconn=2,
            maxconn=10,
            dsn=db_url,
            cursor_factory=RealDictCursor,
        )
        if _PGVECTOR_AVAILABLE:
            # Register pgvector type on one connection to activate globally
            conn = _pool.getconn()
            try:
                register_vector(conn)
            finally:
                _pool.putconn(conn)
    return _pool


@contextmanager
def get_connection():
    """Context-managed PostgreSQL connection from the shared pool."""
    conn_pool = _get_pool()
    conn = conn_pool.getconn()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn_pool.putconn(conn)


def upsert_competitor(payload: Dict[str, Any]) -> None:
    """
    Insert or update a competitor profile extracted by Agent 1.
    Uses ON CONFLICT to update existing records by domain.
    """
    sql = """
    INSERT INTO competitor_profiles (
        pipeline_id, competitor_domain, targeted_seo_keywords,
        estimated_monthly_organic_traffic, monetization_infrastructure,
        affiliate_networks_detected, status
    ) VALUES (%s, %s, %s, %s, %s, %s, 'VERIFIED_PRODUCTION')
    ON CONFLICT (competitor_domain) DO UPDATE SET
        targeted_seo_keywords = EXCLUDED.targeted_seo_keywords,
        estimated_monthly_organic_traffic = EXCLUDED.estimated_monthly_organic_traffic,
        monetization_infrastructure = EXCLUDED.monetization_infrastructure,
        affiliate_networks_detected = EXCLUDED.affiliate_networks_detected,
        status = 'VERIFIED_PRODUCTION';
    """
    traffic = payload.get("estimated_monthly_organic_traffic")
    if isinstance(traffic, str):
        traffic = None

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (
                str(uuid.uuid4()),
                payload["competitor_domain"],
                Json(payload.get("targeted_seo_keywords", [])),
                traffic,
                Json(payload.get("monetization_infrastructure", [])),
                Json(payload.get("affiliate_networks_detected", [])),
            ))
    print(f"[DB] Upserted competitor: {payload['competitor_domain']}")


def persist_strategy_report(report: Dict[str, Any]) -> None:
    """Insert a new strategy report generated by Agent 2."""
    sql = """
    INSERT INTO strategy_reports (
        pipeline_id, competitor_domain, market_gap_analysis,
        recommended_seo_targets, affiliate_opportunity_score,
        dashboard_recommendations, generated_at
    ) VALUES (%s, %s, %s, %s, %s, %s, %s);
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (
                str(uuid.uuid4()),
                report["competitor_domain"],
                report.get("market_gap_analysis"),
                Json(report.get("recommended_seo_targets", [])),
                report.get("affiliate_opportunity_score"),
                Json(report.get("dashboard_recommendations", [])),
                report.get("generated_at"),
            ))
    print(f"[DB] Persisted strategy report for: {report['competitor_domain']}")


def log_hitl_review(
    pipeline_id: str,
    ragas_scores: Dict[str, float],
    composite_score: float,
    raw_payload: Dict[str, Any],
) -> None:
    """Log a low-confidence payload into the manual_review_queue table."""
    sql = """
    INSERT INTO manual_review_queue (
        pipeline_id, ragas_scores, composite_score, raw_payload, assigned_evaluator
    ) VALUES (%s, %s, %s, %s, 'Aastha Shukla');
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (
                pipeline_id,
                Json(ragas_scores),
                composite_score,
                Json(raw_payload),
            ))
    print(f"[DB] Logged HITL review record for pipeline: {pipeline_id}")


def upsert_vector_chunk(
    parent_id: str,
    content: str,
    embedding: List[float],
    chunk_index: int,
    content_hash: str,
) -> None:
    """Insert a child vector chunk or soft-delete and replace on hash change."""
    sql = """
    INSERT INTO competitor_children (parent_id, content, embedding, chunk_index, content_hash)
    VALUES (%s, %s, %s, %s, %s)
    ON CONFLICT DO NOTHING;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (
                parent_id, content, embedding, chunk_index, content_hash
            ))


def similarity_search(
    query_embedding: List[float],
    k: int = 4,
    threshold: float = 0.85,
) -> List[Dict[str, Any]]:
    """
    Execute HNSW cosine similarity search.
    Returns top-k child chunks and their parent context.
    """
    sql = """
    SELECT
        c.child_id,
        c.content AS child_content,
        c.chunk_index,
        p.content AS parent_content,
        p.competitor_domain,
        1 - (c.embedding <=> %s::vector) AS similarity
    FROM competitor_children c
    JOIN competitor_parents p ON c.parent_id = p.parent_id
    WHERE c.is_active = TRUE
      AND 1 - (c.embedding <=> %s::vector) >= %s
    ORDER BY c.embedding <=> %s::vector
    LIMIT %s;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (query_embedding, query_embedding, threshold, query_embedding, k))
            return [dict(row) for row in cur.fetchall()]
